/**
 * Template generation pipeline (§7.1).
 *
 *   Stripe OpenAPI spec
 *     -> event-type list (webhook_endpoint.enabled_events enum)
 *     -> per event: resolve data.object resource (scripts/lib/stripe-events)
 *     -> depth-bounded sample of that resource schema (scripts/lib/sample)
 *     -> committed template at src/schemas/templates/stripe/<apiVersion>/<event>.json
 *     -> static-import manifest at src/schemas/generated.ts (so tsup can bundle)
 *
 * Run on a machine with network access: `yarn generate`.
 * Unmapped event types are logged and skipped — never silently wrong.
 */
import { writeFile, mkdir } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { eventToResource } from "./lib/stripe-events.js";
import { sampleSchema } from "./lib/sample.js";

const SPEC_URL =
  process.env.STRIPE_SPEC_URL ??
  "https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json";
const API_VERSION = process.env.STRIPE_API_VERSION ?? "2024-06-20";

const here = dirname(fileURLToPath(import.meta.url));
const TEMPLATE_DIR = resolve(here, "../src/schemas/templates/stripe", API_VERSION);
const MANIFEST = resolve(here, "../src/schemas/generated.ts");

/**
 * Locate the event-type enum by searching for the array that contains known
 * event strings. Stripe keeps it under POST /v1/webhook_endpoints, but discovery
 * keeps us resilient if that path moves.
 */
function discoverEventTypes(spec: unknown): string[] {
  const NEEDLES = ["customer.subscription.created", "charge.succeeded"];
  let best: string[] = [];
  const walk = (node: unknown) => {
    if (Array.isArray(node)) {
      if (node.some((x) => typeof x === "string" && NEEDLES.includes(x)) && node.length > best.length) {
        best = node as string[];
      }
      for (const v of node) walk(v);
    } else if (node && typeof node === "object") {
      for (const v of Object.values(node as Record<string, unknown>)) walk(v);
    }
  };
  walk(spec);
  return best.filter((e) => typeof e === "string" && e && e !== "*");
}

async function main() {
  console.log(`Fetching Stripe OpenAPI: ${SPEC_URL}`);
  const res = await fetch(SPEC_URL);
  if (!res.ok) throw new Error(`spec fetch failed: ${res.status} ${res.statusText}`);
  const spec: any = await res.json();

  const schemas: Record<string, any> = spec.components?.schemas ?? {};
  const has = (k: string) => Object.prototype.hasOwnProperty.call(schemas, k);

  const events: string[] = discoverEventTypes(spec);

  if (!events.length) {
    console.error(
      "No event types found (webhook_endpoint.enabled_events enum was empty).\n" +
        "Stripe's spec layout may have changed — inspect components.schemas and adjust this path.",
    );
    process.exit(1);
  }
  console.log(`Found ${events.length} event types. Writing to ${TEMPLATE_DIR}`);

  await mkdir(TEMPLATE_DIR, { recursive: true });
  const written: string[] = [];
  const skipped: string[] = [];

  for (const type of events) {
    const resource = eventToResource(type, has);
    if (!resource) {
      skipped.push(type);
      continue;
    }
    const object = sampleSchema({ $ref: `#/components/schemas/${resource}` }, { schemas, maxDepth: 6 });
    const template = { id: "evt_{{seed}}", object: "event", api_version: API_VERSION, type, data: { object } };
    await writeFile(resolve(TEMPLATE_DIR, `${type}.json`), JSON.stringify(template, null, 2) + "\n");
    written.push(type);
  }

  const imports = written
    .map((t, i) => `import t${i} from "./templates/stripe/${API_VERSION}/${t}.json";`)
    .join("\n");
  const entries = written.map((t, i) => `  "stripe/${API_VERSION}/${t}": t${i},`).join("\n");
  const manifest =
    `// AUTO-GENERATED by scripts/generate.ts — do not edit.\n` +
    `${imports}\n\nexport const generated: Record<string, object> = {\n${entries}\n};\n`;
  await writeFile(MANIFEST, manifest);

  console.log(`\nGenerated ${written.length} templates + manifest (src/schemas/generated.ts).`);
  if (skipped.length) {
    console.warn(`\nSkipped ${skipped.length} event types (no resource mapping):`);
    const keys = Object.keys(schemas);
    for (const t of skipped) {
      const tokens = t.split(".").slice(0, -1);
      const probe = tokens[tokens.length - 1] ?? t;
      const suggestions = keys.filter((k) => k.includes(probe)).slice(0, 5);
      console.warn(`  ${t}  → candidate schemas: ${suggestions.join(", ") || "(none found)"}`);
    }
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
